chore: Enable skipLibCheck in TypeScript configuration
Because TypeDoc throws errors from `node_modules`:

```
node_modules/vitest/dist/chunks/reporters.D7Jzd9GS.d.ts:725:5 - error TS18028: Private identifiers are only available when targeting ECMAScript 2015 and higher.

725     #private;
        ~~~~~~~~
```